apiVersion: v1
kind: Secret
metadata:
  name: edgeguard-secrets
  namespace: edgeguard
  annotations:
    edgeguard.io/secret-template: replace-before-production
type: Opaque
stringData:
  # need to change before production deployment
  POSTGRES_USER: edgeguard
  POSTGRES_PASSWORD: change-me-postgres
  POSTGRES_DB: edgeguard
  AUTH_JWT_SECRET: change-me-jwt-secret-with-at-least-32-characters
  RABBITMQ_USERNAME: edgeguard
  RABBITMQ_PASSWORD: change-me-rabbitmq
  RABBITMQ_VHOST: edgeguard
